language: bash

env:
  global:
  - IMAGE_NAME: guangie88/filewatch-aws-trigger

matrix:
  include:
  - service: docker
    env:
    - DOCKER=true
    - DOCKERFILE=Dockerfile
    - TEST=false
  - service: docker
    env:
    - DOCKER=true
    - DOCKERFILE=Dockerfile-test
    - TEST=true
  - python: "3.6"
    env:
    - NATIVE=true
  - python: "3.7-dev"
    env:
    - NATIVE=true

before_install:
- set -e

install:
- |
  if [ "$NATIVE" = "true" ]; then
    python3 -m pip install -r requirements.txt;
    python3 -m pip install -r requirements.dev.txt;
  fi

before_script:
- |
  if [ "$DOCKER" = "true" ] && [ "$TEST" = "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  fi
- |
  if [ "$DOCKER" = "true" ]; then
    docker build -f $DOCKERFILE -t $IMAGE_NAME . ;
  fi

script:
- |
  if [ "$DOCKER" = "true" ] && [ "$TEST" = "true" ]; then
    docker run --rm -it $IMAGE_NAME;
  elif [ "$NATIVE" = "true" ]; then
    pylint *.py;
  fi

after_success:
- |
  if [ "$DOCKER" = "true" ] && [ "$TEST" = "false" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    docker push $IMAGE_NAME:latest
  fi

branches:
  only:
  - master
