language: bash

env:
  global:
  - IMAGE_NAME: guangie88/filewatch-trigger

matrix:
  include:
  - service: docker
    env:
    - PYTHON_VERS=3.6
    - DOCKERFILE=Dockerfile
    - TEST=false
  - service: docker
    env:
    - PYTHON_VERS=3.7
    - DOCKERFILE=Dockerfile
    - TEST=false
  - service: docker
    env:
    - PYTHON_VERS=3.6
    - DOCKERFILE=Dockerfile-test
    - TEST=true
  - service: docker
    env:
    - PYTHON_VERS=3.7
    - DOCKERFILE=Dockerfile-test
    - TEST=true

before_script:
- set -e
- |
  if [ "$TEST" = "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  fi
- docker build --build-arg PYTHON_VERS=$PYTHON_VERS -f $DOCKERFILE -t $IMAGE_NAME .

script:
- |
  if [ "$TEST" = "true" ]; then
    docker run --rm -it $IMAGE_NAME
  fi

after_success:
- |
  if [ "$TEST" = "false" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    docker tag $IMAGE_NAME $IMAGE_NAME:python-$PYTHON_VERS
    docker push $IMAGE_NAME:python-$PYTHON_VERS

    if [ -n "$TRAVIS_TAG" ]; then
      docker tag $IMAGE_NAME $IMAGE_NAME:${TRAVIS_TAG}_python-${PYTHON_VERS}
      docker push $IMAGE_NAME:${TRAVIS_TAG}_python-${PYTHON_VERS}
    fi
  fi

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+(-\S*)?$/
