language: bash

env:
  global:
  - IMAGE_NAME: guangie88/filewatch-aws-trigger

matrix:
  include:
  - service: docker
    env:
    - DOCKER=true
    - DOCKERFILE=Dockerfile
  - service: docker
    env:
    - DOCKER=true
    - DOCKERFILE=Dockerfile-test
    - TEST=true
  - python: "3.6"
    env:
    - NATIVE=true
  - python: "3.7-dev"
    env:
    - NATIVE=true

install:
- |
  if [ "$NATIVE" = "true" ]; then
    python3 -m pip install -r requirements.txt;
    python3 -m pip install -r requirements.dev.txt;
  fi

before_script:
- |
  if [ "$DOCKER" = "true" ]; then
    docker build -f $DOCKERFILE -t $IMAGE_NAME . ;
  fi

script:
- |
  if [ "$DOCKER" = "true" ] && [ "$TEST" = "true" ]; then
    docker run --rm -it $IMAGE_NAME;
  elif [ "$NATIVE" = "true" ]; then
    pylint *.py;
  fi

branches:
  only:
  - master
